In [2]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
import mplfinance as mpf
import talib as tb

In [3]:
#define stock ticker and get stock data from Yahoo finance
tickerSymbol = 'AAPL'
tickerData = yf.Ticker(tickerSymbol)
df = tickerData.history(period="1d", start='2007-3-8', end='2023-3-8')

In [4]:
#drop irrelevant columns
df.drop(['Stock Splits', 'Dividends'], axis=1, inplace=True)
df

,Open,High,Low,Close,Volume
Date,,,,,
2007-03-08 00:00:00-05:00,2.692877,2.696828,2.658528,2.674942,511011200
2007-03-09 00:00:00-05:00,2.699262,2.700781,2.656706,2.674032,451836000
2007-03-12 00:00:00-04:00,2.677071,2.735434,2.674640,2.731786,729408400
2007-03-13 00:00:00-04:00,2.717803,2.753975,2.687102,2.687102,867890800
2007-03-14 00:00:00-04:00,2.693183,2.735739,2.672513,2.735739,796586000
...,...,...,...,...,...
2023-03-01 00:00:00-05:00,146.830002,147.229996,145.009995,145.309998,55479000
2023-03-02 00:00:00-05:00,144.380005,146.710007,143.899994,145.910004,52238100
2023-03-03 00:00:00-05:00,148.039993,151.110001,147.330002,151.029999,70732300
2023-03-06 00:00:00-05:00,153.789993,156.300003,153.460007,153.830002,87558000
2023-03-07 00:00:00-05:00,153.699997,154.029999,151.130005,151.600006,56182000

In [5]:
# Calculate the technical indicators
df["RSI"] = tb.RSI(df['Close'].values, timeperiod=14)
df['SMA20'] = tb.SMA(df['Close'], timeperiod=20)
df['SMA50'] = tb.SMA(df['Close'], timeperiod = 50)

In [6]:
df.columns

Index(['Open', 'High', 'Low', 'Close', 'Volume', 'RSI', 'SMA20', 'SMA50'], dtype='object')

In [7]:
# Create empty lists for S/R levels and define resistance and support level functions
resistance_levels = []
support_levels = []

def isResistance(df,i):
    return df['High'][i] > df['High'][i-1] and df['High'][i] > df['High'][i+1] and df['High'][i+1] > df['High'][i+2] and df['High'][i-1] > df['High'][i-2]

def isSupport(df,i):
    return df['Low'][i] < df['Low'][i-1]  and df['Low'][i] < df['Low'][i+1] and df['Low'][i+1] < df['Low'][i+2] and df['Low'][i-1] < df['Low'][i-2]

In [8]:
# itereate over df to get S/R levels
for i in range(2,df.shape[0]-2):
    if isSupport(df,i):
        support_levels.append((i,df['Low'][i]))
    elif isResistance(df,i):
        resistance_levels.append((i,df['High'][i]))

In [9]:
# display number of levels found
print(len(resistance_levels))
print(len(support_levels))

273
283

In [10]:
#check average candle size
avg_candlesize = np.mean(df['High'] - df['Low'])

In [11]:
# def isFarFromLevel(l):
#    return np.sum([abs(l-x) < s for x in levels or abs(l-x) < s for x in levelr]) == 0

# function to check if a level is far from existing levels
def isFarFromLevel(l):
    # check if l is far from support levels
    far_from_support = np.sum([abs(l-x) < avg_candlesize for x in updated_support_levels]) == 0
    # check if l is far from resistance levels
    far_from_resistance = np.sum([abs(l-x) < avg_candlesize for x in updated_resistance_levels]) == 0
    return far_from_support or far_from_resistance

In [12]:
# store update S/R levels 
updated_support_levels = []
updated_resistance_levels = []

for res in resistance_levels:
    if isFarFromLevel(res[1]):
        updated_resistance_levels.append(res)
        
for sup in support_levels:
    if isFarFromLevel(sup[1]):
        updated_support_levels.append(sup)

In [13]:
#  check number of updated s/r levels
print(len(updated_support_levels))
print(len(updated_resistance_levels))

78
273

In [14]:
#  initialise the required columns to zero  
df['Resistance'] = 0
df['Support'] = 0

In [15]:
# find s/r levels and mark them 1 in respective columns
for index, row in df.iterrows():
    high_value = row['High']
    if any(high_value == url[1] for url in updated_resistance_levels):
        df.at[index, 'Resistance'] = 1
    
    low_value = row['Low']
    if any(low_value == usl[1] for usl in updated_support_levels):
        df.at[index,'Support'] = 1

In [16]:
# print support levels for debugging purpose 
for index, row in df.iterrows():
    if row['Support']==1:
        print(row["Low"])

2.8035238720349183
3.915448020020122
5.379979089454621
6.6919195335994965
9.145570175539405
10.483954066770133
11.87766170759641
18.06802339866048
16.98376117297166
20.06425758995158
19.044641038192342
13.340156655468501
22.528905312620164
21.508725994730582
23.875891375652184
26.71542192012312
28.56067277014009
25.39312990530687
32.52284474626878
33.613831160704265
35.26975716484367
36.685421140258256
39.090748263310346
40.24719003840182
44.44295274389651
43.239514473566786
48.93127342407363
51.34049958917693
47.578312269361746
41.3570767703343
50.2128846887297
52.4517061001283
57.84731148366074
62.6746826448777
68.12072821217335
73.90669058484998
76.93292005344043
64.4682387378654
81.74481549240832
84.83441011014459
86.34108830478004
94.226021285989
107.4635185048495
109.21915181574397
108.34255150386265
103.41788763767384
105.70294688474958
112.60426401105487
111.0848371254699
118.5437878699246
121.7996646168325
125.16408025377994
128.4693174150815
114.82778815834044
129.73832489841544
121.00113881626868
121.60489928473106
131.4532448076695
140.22275088825288
144.03113852000487
145.54777508446023
140.03634254536453
137.98438512573023
166.23989049320429
175.96847579858
153.57286427093453
169.65227947323717
151.08477872553206
149.19621570320402
164.50348894628465
162.5851121901809
152.34713293610744
138.16697435225757
133.15990815675642
147.89847229742568
133.9429531596724
134.17513508781377
140.13604619898288

In [17]:
#print resistance levels for debugging purpose
for index, row in df.iterrows():
    if row['Resistance']==1:
        print(row["High"])

2.943348551861051
3.4956643459527528
3.805107612085818
3.8023726481253513
4.254983957726591
4.414264878711551
4.526735161613293
4.114852148191921
4.433108864789269
4.237354832075042
5.732890897665112
5.779093951968967
5.856909946038906
5.397609497296502
5.705531932939421
5.983059057268732
6.169392320116661
4.1537601858141056
4.018496188292313
4.4300695874128735
4.854110410604534
5.121908941944067
5.720731134249646
5.764806898180841
5.542605104118388
5.499136242141459
4.930406744661042
5.485154825812973
3.5382205756243024
3.4102488639373636
2.783764821192714
2.925112054683454
2.8384798615549967
2.887722637361535
3.130899690466858
3.03788411458148
2.824496961177302
3.1454904641201606
3.677439794889834
3.7768374059357335
3.8665080270291883
4.058010607512503
3.9306448646745094
5.127077123551916
5.3033797566374705
5.677869699206226
5.742009420772482
5.696412604127308
6.34417560465444
6.231402774547237
6.0702968460548865
6.50345556842505
6.553308157793661
6.552092319052496
6.085495683798238
6.210428920650098
6.922327302232605
8.281988729117758
8.224537314187222
8.055226095194495
8.48108832420248
8.085318682219208
8.03333709211857
8.958933435317832
9.766585256995784
9.657157095835686
9.92951129687813
10.505230792711247
11.091896565350782
10.993713052531163
10.835952270657177
10.770297937837219
10.638980648619425
10.408267160275107
10.703723216929008
10.234698545887595
10.9429521538219
12.295622496790628
11.918091577621897
11.812614969443567
12.853712639806462
12.970437471898036
11.889516979897914
12.049708557008229
12.435143200220885
13.002349352761561
18.531582985412022
18.89026439858646
19.57572317113485
17.505078645066387
17.67590196431565
17.93427816950245
18.842237355055218
18.59146659962399
20.859199748160524
20.583227268252976
19.757455488061726
19.928112001915526
16.403793076170658
17.020200816835395
15.793208532035488
14.958342166663357
13.541595591549584
14.495964890494006
13.51013060994381
13.502683948023193
16.056907916644228
15.697487049486174
15.530895970453898
16.530426572524195
17.97843541041891
17.611243854733523
17.43171717080253
16.911786570510102
17.36245829761176
17.187882214903727
16.83240630421424
16.829247966693927
18.957335039901324
21.159620547518617
21.549201809335802
22.13690611279068
23.209017377517757
22.898052374488547
22.904761636078522
24.676641288477523
26.33403315276043
25.500420774338583
25.788027819713946
26.963172218273087
30.137480539872723
29.22838431851063
29.156193542480466
29.002800715142783
30.34952067243928
29.453965995505836
30.12064735457429
29.488656074114406
30.12064709339463
26.55251543737798
25.655978504043887
28.174924239459962
27.40429741572476
27.39058631990215
23.124089108087517
23.20179130293014
22.36268629992843
22.137520825089602
23.837755255309194
24.733829996753244
25.822900514939796
22.034129231948448
23.284788596806887
23.552928262227816
23.347199468190613
24.537674477191295
25.277201947142167
27.00169712989524
27.585060564760845
26.09845183953756
27.448695378393843
28.602707646380605
31.97149681462114
32.91231787339204
33.50355114518564
33.90240734099075
34.127646510117316
33.99625450581617
34.74468754149297
36.90472288956916
36.74688059951632
34.93286347054603
38.12506895580289
38.43560511490425
39.01033479791422
38.77854998154154
36.593179606843336
38.04773611471102
41.68292999267578
41.65712433135424
41.78054807324556
41.6832307336564
40.02407162855606
41.66490403552554
43.04721889505823
43.73360911691656
42.64681472803525
45.471726250230816
45.373632510779984
46.46221365561134
46.146397427045365
45.06260801816764
46.09137074212721
46.88329735454585
52.62256021487734
55.14108578835079
54.824174220637246
56.05343028655414
53.386048289795966
50.62338171512649
41.57661638796032
38.39398025606666
37.23030860456871
38.03740540468266
42.29939407550225
42.55339511545279
43.00826704632719
50.44368250679571
46.749264332468556
48.78468491634835
52.28347085716567
55.204368611961364
54.55582231864857
55.643228490206326
56.06014607871478
58.05943347079796
65.5383345762006
66.27195496371452
73.51053072743386
80.17439108103741
79.53124881245057
80.21025261765767
79.58027057408931
74.5184131788004
63.40927653312242
78.57659102024277
87.19889825709467
91.5272508776146
97.5785947976653
109.75749465907809
135.90096165705006
117.03952378697038
123.50067530650824
124.26623679573483
127.84772518808066
136.93461117641147
130.85696191463055
127.18900063416238
125.7068380903118
122.76228911077312
148.46764161370334
148.2993870088357
150.35541177479374
149.54257709681752
146.18220877735166
151.09887270060366
179.82020271706764
180.0088334194508
181.60711561437049
175.8890553789366
174.95593533648793
175.58634945696326
172.29628395278138
167.89296659074904
178.52853282999885
170.49717014343693
165.4775769530988
151.04793276317986
149.18646404482885
142.83557151358974
155.56723656273138
162.88373165018353
175.59017572668876
170.5064012608413
163.73796277204346
158.2355106664936
154.22829438707754
147.07109880642605
152.00538263644177
151.5985423428866
143.10151982010217
147.0055407027821
156.3300018310547

In [18]:
# Define the trading signals based on the SMA20, SMA50, RSI, and support/resistance levels
df['Signal'] = np.where((df['SMA20'] > df['SMA50'])  & (df['Support']==1), 1,np.where((df['SMA20'] < df['SMA50']) & (df['Resistance']==1), -1, 0))

In [19]:
# df[df['Signal'] == 1]

,Open,High,Low,Close,Volume,RSI,SMA20,SMA50,Resistance,Support,Signal
Date,,,,,,,,,,,
2007-07-10 00:00:00-04:00,3.917576,4.088407,3.915448,4.023054,1255007600,67.527455,3.764633,3.541430,0,1,1
2007-12-04 00:00:00-05:00,5.384843,5.498832,5.379979,5.465699,773799600,55.890595,5.266295,5.223465,0,1,1
2010-03-22 00:00:00-04:00,6.701647,6.869743,6.691920,6.831746,456419600,67.293114,6.572260,6.318764,0,1,1
2010-10-29 00:00:00-04:00,9.247705,9.297860,9.145570,9.148914,430511200,54.797467,9.175512,8.521063,0,1,1
2011-03-10 00:00:00-05:00,10.612229,10.631988,10.483954,10.537757,507539200,46.708618,10.728940,10.482635,0,1,1
2011-10-21 00:00:00-04:00,12.101081,12.132694,11.877662,11.942103,621244400,48.308114,11.998642,11.816770,0,1,1
2012-03-23 00:00:00-04:00,18.253142,18.292962,18.068023,18.118179,430488800,76.816170,17.113999,15.348728,0,1,1
2012-05-08 00:00:00-04:00,17.313569,17.371931,16.983761,17.271013,497252000,42.772305,17.937760,17.846687,0,1,1
2012-08-31 00:00:00-04:00,20.369534,20.410746,20.064258,20.308174,338321200,65.217470,19.757069,18.788133,0,1,1
2012-10-15 00:00:00-04:00,19.304126,19.388992,19.044641,19.377697,432502000,38.909770,20.300498,20.155896,0,1,1
2014-08-27 00:00:00-04:00,22.600497,22.947268,22.528905,22.848829,209476000,74.136388,21.876272,21.352338,0,1,1
2014-09-09 00:00:00-04:00,22.166472,23.061364,21.508726,21.922613,759385200,46.632948,22.325764,21.686757,0,1,1
2014-12-16 00:00:00-05:00,23.900608,24.752195,23.875891,23.985991,243162800,34.936191,25.704891,24.421083,0,1,1
2015-02-09 00:00:00-05:00,26.742492,27.033489,26.715422,27.006420,155559200,63.405631,25.572156,25.348327,0,1,1
2015-02-26 00:00:00-05:00,29.052435,29.521642,28.560673,29.420132,365150000,67.796995,28.067543,26.119137,0,1,1
2017-03-27 00:00:00-04:00,32.703502,33.132855,32.522845,33.053085,94300400,65.950050,32.796060,31.144522,0,1,1
2017-04-28 00:00:00-04:00,33.806217,33.855488,33.613831,33.702984,83441600,58.974029,33.533001,33.039244,0,1,1
2017-05-17 00:00:00-04:00,36.186191,36.414711,35.269757,35.396973,203070800,56.717085,34.906039,33.894074,0,1,1
2017-08-21 00:00:00-04:00,37.250685,37.342925,36.685421,37.182098,105474000,55.809479,36.832147,35.402992,0,1,1
2017-11-02 00:00:00-04:00,39.402946,39.852318,39.090748,39.760078,165573600,69.423531,37.721582,37.510896,0,1,1
2017-11-20 00:00:00-05:00,40.420464,40.484553,40.247190,40.346882,65049600,57.979299,40.006231,38.163646,0,1,1
2018-05-23 00:00:00-04:00,44.584113,45.098497,44.442953,45.065002,80233600,65.794944,43.389438,41.859941,0,1,1
2018-06-25 00:00:00-04:00,43.878310,44.241969,43.239514,43.584034,126652400,36.542361,45.267401,43.758692,0,1,1
2018-08-08 00:00:00-04:00,49.297325,49.718402,48.931273,49.584423,90102000,72.102190,46.935566,45.803176,0,1,1
2018-08-22 00:00:00-04:00,51.402925,51.945523,51.340500,51.631008,76072400,74.013140,49.454367,46.836870,0,1,1
2019-07-25 00:00:00-04:00,50.737530,50.822544,50.212885,50.283325,55638400,60.043946,49.466967,47.242231,0,1,1
2019-10-03 00:00:00-04:00,53.256289,53.873142,52.451706,53.839008,114426000,55.667013,53.591537,51.547536,0,1,1
2019-10-31 00:00:00-04:00,60.280578,60.751137,57.847311,60.651173,139162000,70.836731,57.871934,54.714398,0,1,1
2019-12-03 00:00:00-05:00,63.168663,63.467009,62.674683,63.447449,114430400,52.994279,64.305333,59.984339,0,1,1
2019-12-20 00:00:00-05:00,69.018215,69.120920,68.120728,68.335930,275978000,70.093914,66.044784,63.200679,0,1,1
2020-02-03 00:00:00-05:00,74.415343,76.662721,73.906691,75.481567,173788400,52.167817,76.556591,71.009654,0,1,1
2020-02-10 00:00:00-05:00,77.013808,78.820389,76.932920,78.820389,109348800,60.416972,77.623702,72.432778,0,1,1
2020-06-15 00:00:00-04:00,81.909498,84.964665,81.744815,84.303490,138808800,65.962235,80.203838,74.169339,0,1,1
2020-06-19 00:00:00-04:00,87.166962,87.638875,84.834410,85.957672,264476000,67.408073,81.935920,76.030062,0,1,1
2020-06-29 00:00:00-04:00,86.825295,89.017744,86.341088,88.921883,130646000,64.186704,85.056713,78.429175,0,1,1
2020-07-17 00:00:00-04:00,95.354204,95.511505,94.226021,94.705315,92186800,68.363557,91.378429,84.460648,0,1,1
2020-08-11 00:00:00-04:00,110.282891,110.787666,107.463519,107.726990,187902400,65.988400,99.820246,92.423175,0,1,1
2020-09-04 00:00:00-04:00,118.260831,121.836133,109.219152,119.137421,332607200,54.993413,119.030802,105.154503,0,1,1
2020-09-11 00:00:00-04:00,112.843692,113.493751,108.342552,110.312416,180860300,44.224838,119.302025,107.029811,0,1,1
2020-09-24 00:00:00-04:00,103.585324,108.588782,103.417888,106.589371,167743300,42.701365,115.204951,109.867227,0,1,1
2020-11-10 00:00:00-05:00,114.005287,116.018009,112.604264,114.419670,138023400,51.327969,113.950546,113.927039,0,1,1
2020-11-24 00:00:00-05:00,112.387198,114.301258,111.084837,113.630348,113874200,47.215353,114.393612,113.705762,0,1,1
2020-12-10 00:00:00-05:00,118.889107,122.214059,118.543788,121.592476,81312200,59.079815,118.247799,115.959970,0,1,1
2020-12-21 00:00:00-05:00,123.348676,126.594695,121.799665,126.515762,121251600,63.822245,120.778508,117.506396,0,1,1
2021-01-12 00:00:00-05:00,126.782155,127.956249,125.164080,127.078148,91951100,51.570871,128.341531,121.406440,0,1,1
2021-01-29 00:00:00-05:00,134.014183,134.912021,128.469317,130.195923,177523800,49.034229,131.241243,125.937210,0,1,1
2021-04-21 00:00:00-04:00,130.785715,132.159182,129.738325,131.912155,68847100,60.657099,126.453353,124.939872,0,1,1
2021-05-12 00:00:00-04:00,122.139392,123.366723,121.001139,121.515823,112172300,35.488915,129.878086,125.351697,0,1,1
2021-05-19 00:00:00-04:00,121.901838,123.643853,121.604899,123.416206,92612000,41.961714,127.861711,125.909721,0,1,1
2021-07-19 00:00:00-04:00,142.281504,142.598242,140.222751,140.994781,121434600,58.198475,138.735591,130.756843,0,1,1
2021-08-10 00:00:00-04:00,145.161183,146.420096,144.031139,144.328522,69023100,55.711873,145.052694,137.231537,0,1,1
2021-08-27 00:00:00-04:00,146.192093,147.451006,145.547775,147.302322,55802400,55.955865,146.414244,142.755959,0,1,1
2021-09-20 00:00:00-04:00,142.544248,143.575159,140.036343,141.691757,123478900,35.736176,149.114849,146.931526,0,1,1
2021-12-20 00:00:00-05:00,167.053908,169.337153,166.239890,168.513199,107499100,55.645725,167.034055,155.647805,0,1,1
2021-12-31 00:00:00-05:00,176.792430,177.924124,175.968476,176.276230,64062300,61.382942,173.210226,160.868849,0,1,1
2022-01-24 00:00:00-05:00,158.854110,161.117497,153.572864,160.442444,162294600,34.372160,172.146538,167.353313,0,1,1
2022-04-11 00:00:00-04:00,167.694168,168.012233,164.503489,164.751984,72246700,44.031571,169.326273,167.195613,0,1,1
2022-04-18 00:00:00-04:00,162.932996,165.596867,162.585112,164.076080,69023900,44.009224,170.774501,166.622651,0,1,1
2022-05-02 00:00:00-04:00,155.766422,157.277259,152.347133,157.008896,123055300,40.436708,165.003955,164.621175,0,1,1
2022-09-16 00:00:00-04:00,150.729458,150.869013,147.898472,150.221069,162278800,38.302660,159.329520,158.883078,0,1,1

In [20]:
# df[df['Signal'] == -1]

,Open,High,Low,Close,Volume,RSI,SMA20,SMA50,Resistance,Support,Signal
Date,,,,,,,,,,,
2007-08-24 00:00:00-04:00,3.967731,4.114852,3.945844,4.112724,911834000,56.569919,3.939021,3.964278,1,0,-1
2007-09-05 00:00:00-04:00,4.406664,4.433109,4.137041,4.157104,2328222400,54.400171,3.942046,4.018239,1,0,-1
2007-09-12 00:00:00-04:00,4.133701,4.237355,4.126406,4.159842,1022770000,54.043685,4.000727,4.061057,1,0,-1
2008-01-31 00:00:00-05:00,3.934901,4.153760,3.933382,4.114549,1345674400,28.169749,4.822649,5.316401,1,0,-1
2008-02-28 00:00:00-05:00,3.866510,4.018496,3.823043,3.948887,1618254400,46.495772,3.820002,4.664025,1,0,-1
...,...,...,...,...,...,...,...,...,...,...,...
2022-09-27 00:00:00-04:00,152.254591,154.228294,149.473449,151.277695,84442700,42.471944,154.441108,159.745476,1,0,-1
2022-10-06 00:00:00-04:00,145.346601,147.071099,144.758480,144.967804,68402200,41.067902,150.256945,158.500861,1,0,-1
2022-10-25 00:00:00-04:00,149.613001,152.005383,148.885325,151.855850,74732300,58.207938,143.172032,152.749997,1,0,-1
2023-01-23 00:00:00-05:00,137.909435,143.101520,137.689769,140.894882,81760300,61.862064,131.484745,139.003164,1,0,-1
2023-01-27 00:00:00-05:00,142.941753,147.005541,142.861874,145.707520,70555800,67.931544,134.186619,138.894530,1,0,-1

In [21]:
df = df.reset_index(drop=True)

In [22]:
# Initialize variables
positions = []
profit = []
investment = 0

# Loop through the DataFrame
for i, row in df.iterrows():
       # Check if it's a buy signal
    if row['Signal'] == 1:
        # Buy at the open price of the next day
        buy_price = df.loc[i+1, 'Open']
        positions.append({'buy_price': buy_price})
        
    # Check if it's a sell signal
    elif row['Signal'] == -1:
        # Check if there are any open positions
        if len(positions) > 0:
            # Sell all open positions at the close price of the current day
            for pos in positions:
                investment += pos['buy_price']
                profit.append(row['Close'] - pos['buy_price'])
            positions = []
            
# Print the total profit
# print('Total profit: {:.2f}'.format(profit))

In [23]:
df.index

RangeIndex(start=0, stop=4028, step=1)

In [24]:
#display investment and total profit
print(investment,sum(profit))

4749.749048517875 448.5161826146333

In [25]:
profit

[0.09818167699967173,
 -1.4447741424968248,
 1.0736228200071114,
 1.3681717843578944,
 0.05775479456946542,
 -0.09636289768348938,
 -0.8897188553674624,
 0.2073140157277038,
 -0.6456526083474117,
 0.2820786474949273,
 3.5970255248072114,
 4.39795608279649,
 2.2559167042800645,
 2.8088457798810644,
 0.591388260304825,
 4.893006184421523,
 3.909955945239851,
 2.3158633203374706,
 0.5297951384770414,
 -0.05784381368885505,
 0.5585163527831654,
 0.5119832179538832,
 1.8948470535347894,
 3.222529726493903,
 1.8174721378960967,
 12.955392689374378,
 8.33625560073844,
 2.509098908474556,
 -0.4931637044652746,
 -5.252041523566177,
 -13.757359469070721,
 -15.972436317283197,
 32.889983168822,
 32.91948522607558,
 30.771273864831272,
 24.48150542564322,
 10.442756129381848,
 7.042279735518804,
 6.2838823619946,
 12.47909159054403,
 8.008467698906372,
 9.626525469761006,
 2.838516530146407,
 -6.2187584638949716,
 -3.406862151639203,
 -8.330149599069784,
 40.1826389199214,
 48.332922336832596,
 47.68956684508528,
 29.645783687348853,
 26.865672914411107,
 23.94142326829055,
 28.967165428756402,
 1.330248675935053,
 -4.894072399360397,
 13.818588307135428,
 -1.987959912620056,
 0.9939703737095726,
 7.822634322860239,
 4.3959838243237925]